### ISSUE TITLE
setting direction if not known?

### ISSUE THREAD

**Issue by u-fischer** [u-fischer/lua-font-pond#11]
Should the patch (see e.g. fontloader-reference-2018-07-20-patched.lua) in `nodes.simple_font_handler`

~~~~
   if not direction then
             direction = tex.get("textdir") -- experiment
   end
~~~~

 be included and if yes how at best?

It is needed to get the correct spacing in a primitive \halign with RTL-script, see e.g. arabkernsfs.lvt.

~~~~
\halign{#\cr الإشارات برهن\cr}
~~~~

The alternative is

~~~~
\halign{#\cr{\textdir TRT الإشارات برهن}\cr}
~~~~

which probably is done  on user level in latex anyway ...

**Comment by zauguin** [comment]
I think it makes sense to set it, even if it might be done on the user level too.
The actual problem is that we use `simple_font_handler`, a function taking five arguments, and only evet pass the first two arguments. So I fear leaving this to the user level might just let it appear in another situation again.

@u-fischer I just [pushed](https://github.com/u-fischer/lua-font-pond/commit/8536ec25c572d9c4f45eec9fe1f74c6f7b31f7bb#diff-3567010ad4464db42e08c7084920ac2cR659) another way of implementing it by passing the direction as an argument instead of providing a default if the argument is missing.
The advantage is that this only requires changes in `luaotfload-init.lua`, the fontloader does not have to be patched. We still do not pass the `size` and the `packtype` but they are ignored anyway.

**Comment by u-fischer** [comment]
Looks good, on my system and on travis all test passed.
